#!/usr/bin/env python
import logging
import os
import subprocess

import click
import waitress

try:
    from api import app
except ImportError:
    print("Try installing the package `python setup.py install`")
    raise


logging.getLogger("waitress").setLevel(logging.INFO)

@click.command()
@click.option("--dev", is_flag=True)
def start(dev):
    if dev:
        print("Starting development server...")
        env = os.environ.copy()
        env["FLASK_APP"] = "api/app.py"
        env["FLASK_ENV"] = "development"
        subprocess.run(["flask", "run"], env=env)

    else:
        print("Starting production server...")
        waitress.serve(app.app, host="127.0.0.1", port=5000)


if __name__ == "__main__":
    start()
