#!/usr/bin/env python
import os

from rogue_sky import postgres_utilities

DATABASE_URL = os.environ["DATABASE_URL"]
TEST_DATABASE_URL = os.environ["TEST_DATABASE_URL"]


if __name__ == "__main__":
    postgres_utilities.setup_db(
        database_url=DATABASE_URL, test_database_url=TEST_DATABASE_URL
    )
