#!/bin/bash
set -ex # fail on first error, print commands

echo "Checking documentation..."
python3 -m pydocstyle api
echo "Success!"

echo "Checking code style with black..."
python3 -m black --line-length 90 --check api
echo "Success!"

echo "Checking code style with pylint..."
python3 -m pylint api
echo "Success!"

echo "Running unit tests..."
python3 -m pytest
echo "Success!"
