#!/usr/bin/env python
import logging
import os
import subprocess

import click

logging.basicConfig(level=logging.INFO)
_logger = logging.getLogger("__name__")

HOST = os.environ["FRONTEND_HOST"]
PORT = os.environ["FRONTEND_PORT"]


@click.command()
@click.option("--production", is_flag=True)
def start(production):
    """Start frontend server.

    Parameters
    ----------
    production : bool, optional
        Defaults to False.
    """
    if production:
        _logger.info("Building production frontend into `frontend/dist/`")
        subprocess.check_call(["npm", "run", "build"])

    else:
        _logger.info(
            "Starting frontend server:\n\tProduction: %s\n\tHost: %s\n\tPort: %s",
            production,
            HOST,
            PORT,
        )
        subprocess.check_call(
            ["npm", "run", "serve", "--", f"--host={HOST}", f"--port={PORT}"],
            env=os.environ.copy(),
        )


if __name__ == "__main__":
    start()
