#!/usr/bin/env python
import logging
import subprocess

logging.basicConfig(level=logging.INFO)
_logger = logging.getLogger(__name__)


def install():
    _logger.info("Installing frontend...")
    subprocess.check_call("scripts/install", cwd="./frontend")

    _logger.info("Installing backend...")
    subprocess.check_call("scripts/install", cwd="./backend")


if __name__ == "__main__":
    install()
