#!/usr/bin/env python
import subprocess

import click

@click.command()
@click.option("--dev", is_flag=True)
def start(dev):
    if dev:
        print("Starting development server...")
        subprocess.run(["npm", "run", "serve"])

    else:
        print("Starting production server...")
        subprocess.run(["http-server", "dist", "-a" "127.0.0.1"])


if __name__ == "__main__":
    start()
