#!/usr/bin/env python
import logging
import subprocess

import click

logging.basicConfig(level=logging.INFO)
_logger = logging.getLogger(__name__)
# fork (split a process into 2)


@click.command()
@click.option("--production", is_flag=True)
def start(production):
    if production:
        _logger.info("Starting backend...")
        subprocess.Popen(["scripts/start", "--production"], cwd="frontend")
        subprocess.Popen(["scripts/start", "--production"], cwd="backend")

    else:
        _logger.info("Starting backend...")
        subprocess.Popen("scripts/start", cwd="frontend")
        subprocess.check_call("scripts/start", cwd="backend")


if __name__ == "__main__":
    start()
