#!/usr/bin/env python
import logging
import subprocess

import click

logging.basicConfig(level=logging.INFO)
_logger = logging.getLogger(__name__)


@click.command()
@click.option("--production", is_flag=True)
def start(production):
    backend_script = ["scripts/start"]
    frontend_script = ["scripts/start"]

    if production:
        backend_script.append("--production")
        frontend_script.append("--production")

    with subprocess.Popen("scripts/start", cwd="backend") as _:
        subprocess.check_call("scripts/start", cwd="frontend")


if __name__ == "__main__":
    start()
