#!/usr/bin/env python
import logging
import subprocess

import click

logging.basicConfig(level=logging.INFO)
_logger = logging.getLogger(__name__)


@click.command()
@click.option("--it", is_flag=True)
def test(it):
    _logger.info("Testing backend...")
    backend_command = "scripts/test-it" if it else "scripts/test"
    subprocess.check_call(backend_command, cwd="backend")

    _logger.info("Testing frontend...")
    subprocess.check_call("scripts/test", cwd="./frontend")

    _logger.info("Success!")


if __name__ == "__main__":
    test()
